// Generated by CoffeeScript 2.6.1
import {
  cpus
} from 'os';

export default (max = cpus().length * 2) => {
  var n, todo;
  n = 0;
  todo = [];
  return (func) => {
    if (n < max) {
      ++n;
      return func().finally(() => {
        if (todo.length) {
          return setImmediate(async() => {
            var err, reject, resolve;
            while (todo.length) {
              [func, resolve, reject] = todo.shift();
              try {
                resolve((await func()));
              } catch (error) {
                err = error;
                reject(err);
              }
            }
            return --n;
          });
        }
      });
    }
    return new Promise((resolve, reject) => {
      todo.push([func, resolve, reject]);
    });
  };
};
