// Generated by CoffeeScript 2.6.1
//!/usr/bin/env coffee
var Translate;

import axios from '@rmw/axios';

export default Translate = class Translate {
  constructor(option = {}, url = "https://api-free.deepl.com/v2/translate") {
    this.url = url;
    this.option = {
      source_lang: "ZH",
      ...option
    };
  }

  post(option) {
    console.log(option);
    return axios.post(this.url, option);
  }

  txt(text, target_lang = "EN-US", option = {}) {
    return option = {text, target_lang, ...this.option, ...option};
  }

  xml(text, target_lang = "EN-US", option = {}) {
    return this.post({
      text,
      target_lang,
      tag_handling: "xml",
      ignore_tags: "code,pre,img,iframe,video,script,var",
      non_splitting_tags: "code,a,b,strong,em,del,i,span",
      ...this.option,
      ...option
    });
  }

};
