// Generated by CoffeeScript 2.6.1
import {
  pipeline
} from 'stream/promises';

import {
  createReadStream
} from 'fs';

import {
  parse
} from '@fast-csv/parse';

export var stream = async function*(stream, option) {
  var csv, p;
  csv = parse({
    headers: true,
    ...option
  });
  p = pipeline(stream, csv);
  yield* csv;
  return (await p);
};

export default function(file, option) {
  return stream(createReadStream(file), option);
};
